### PR TITLE
Attempt to track trait uses for Paladin and Sorcerer

### PR DESCRIPTION
**Pull request by dhleong**
Lay on Hands pool and sorcery points.

I can't figure out how to actually run this thing locally to test (see #3) but these look about right. The Lay on Hands one might get quite unwieldy to use at higher levels, but it's a start.

### CODE REVIEW

**Comment by larrychristensen** [comment]
Thanks, I've added more instructions on messenjer on how to get the code running. As for the frequency, I don't think it's going to do what you want it to do. Frequency is intended to show how many time a trait can be used per short rest, long rest, etc. It would sort of work to do it the way you did, but it will add a ton of checkboxes--100 for a 20th level paladin.

**Comment by dhleong** [comment]
Unfortunately that doesn't seem to help with the datomic database stuff; I get:

```clojure
orcpub.server=> (def system-map (com.stuartsierra.component/start (orcpub.system/system :dev)))

CompilerException clojure.lang.ExceptionInfo: Error in component :conn in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :conn, :component #orcpub.datomic.DatomicComponent{:uri "?aws_access_key_id=&aws_secret_key=", :conn nil}, :system #<SystemMap>}, compiling:(form-init387975425768735324.clj:1:17) 
```

Yes it's definitely too many checkboxes as-is for Paladin, but it might be sufficient for Sorcerer, and could yet be a starting point for Paladin. Its use here does seem to be appropriate, since I believe Lay on Hands is a pool that is recharged on long rest, but it's corresponding UI is perhaps not ready to handle this specific case. Maybe for large numbers of uses it could turn into a dropdown instead of a list of checkboxes? I haven't quite discovered where this thing is rendered yet....

**Comment by larrychristensen** [comment]
Oh, yeah, I'll add instructions on that tomorrow.

**Comment by dhleong** [comment]
Okay! Thank you for adding that info on setting up the local DB. I was able to pretty easily set up datomic using homebrew with:

```
$ brew install datomic
$ brew services start datomic
```

and then with your instructions was good to go.

I've pushed another commit that implements what I discussed for actions with an `amount` that would be higher than practically manageable with checkboxes. It currently makes use of the `toggle-feature-used` event in a way that perhaps wasn't intended, but I think makes sense, and would be more efficient (storage-wise, anyway) once you get up to the 10s of numbers. When you transition from checks to dropdown, completing a long rest would fix any inconsistency.

What do you think?

**Comment by larrychristensen** [comment]
The code looks good, so you were able to test it out, including round-trip from the back-end?

**Comment by dhleong** [comment]
Deleted my DB so it'll take me a bit to get a user created again and verify the roundtrip (the email verification step doesn't seem to work from local so I did it manually last time) but I did test the UI. I'm assuming that the backend round trip should be fine because the data is in the same format as for the checkbox mode....

**Comment by larrychristensen** [comment]
Yeah, looking at the code again, I think that's the case. I'll merge, but it might take me a couple of days before I can test it out myself and deploy. Thanks again, your code looks great!

**Comment by larrychristensen** [comment]
I've deployed this, please try it out with both light and dark themes.

**Comment by dhleong** [comment]
Seems to work for me, thanks!

**Comment by larrychristensen** [comment]
I noticed a couple of things:
1. With dark theme, the dropdown has black characters on black background so you can't see any of the items.
2. It seems like it defaults to the max number, like 100 for a level 20 paladin, I believe it should default to 0.

**Comment by larrychristensen** [comment]
Thanks for your outstanding work, by the way.

**Comment by dhleong** [comment]
> With dark theme, the dropdown has black characters on black background so you can't see any of the items.

Hmm... I don't see that on my browser. Chrome on macOS must not style dropdowns?

> It seems like it defaults to the max number, like 100 for a level 20 paladin, I believe it should default to 0.

This is to indicate uses remaining.

> Thanks for your outstanding work, by the way.

Glad to help :)

**Pull request merged**
